insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (1, '08761 Delaware Circle', 'Shreveport', 'LA', '71137');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (2, '0 Hudson Center', 'Tulsa', 'OK', '74133');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (3, '2 Tomscot Plaza', 'Palm Bay', 'FL', '32909');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (4, '06158 Continental Terrace', 'Eugene', 'OR', '97405');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (5, '8588 Mesta Hill', 'Loretto', 'MN', '55598');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (6, '3935 Eggendart Way', 'Charlotte', 'NC', '28235');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (7, '47656 Sutherland Place', 'Columbus', 'OH', '43220');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (8, '9467 Clemons Lane', 'Honolulu', 'HI', '96845');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (9, '55 Aberg Drive', 'Atlanta', 'GA', '30301');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (10, '6897 Weeping Birch Street', 'Memphis', 'TN', '38126');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (11, '03 Fallview Road', 'Irvine', 'CA', '92710');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (12, '2596 Longview Plaza', 'Austin', 'TX', '78754');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (13, '155 Kennedy Hill', 'Las Vegas', 'NV', '89120');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (14, '5464 Elmside Street', 'Albany', 'NY', '12255');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (15, '96206 Muir Way', 'Columbia', 'SC', '29220');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (16, '7167 Esch Terrace', 'Minneapolis', 'MN', '55402');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (17, '3 Saint Paul Hill', 'Dallas', 'TX', '75265');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (18, '80751 Dorton Way', 'Fresno', 'CA', '93704');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (19, '70 Delaware Circle', 'Dayton', 'OH', '45490');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (20, '94670 Buell Point', 'Norfolk', 'VA', '23509');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (21, '2339 8th Crossing', 'Stamford', 'CT', '06905');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (22, '83094 Hooker Circle', 'Pueblo', 'CO', '81005');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (23, '7016 Tony Terrace', 'Evansville', 'IN', '47719');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (24, '46872 Hagan Court', 'Scottsdale', 'AZ', '85255');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (25, '8433 Dayton Court', 'Virginia Beach', 'VA', '23454');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (26, '21343 Orin Drive', 'Miami', 'FL', '33147');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (27, '90931 Nancy Junction', 'Young America', 'MN', '55557');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (28, '5400 Coleman Parkway', 'Montgomery', 'AL', '36177');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (29, '04361 Walton Circle', 'Frankfort', 'KY', '40618');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (30, '4455 Crownhardt Parkway', 'Tampa', 'FL', '33694');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (31, '7990 Messerschmidt Hill', 'Charlotte', 'NC', '28278');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (32, '2022 Miller Trail', 'Houston', 'TX', '77228');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (33, '92 Namekagon Way', 'Houston', 'TX', '77260');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (34, '336 Ridge Oak Pass', 'Anchorage', 'AK', '99507');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (35, '93 Rusk Point', 'New York City', 'NY', '10150');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (36, '896 Granby Junction', 'Lexington', 'KY', '40586');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (37, '076 Gerald Junction', 'Phoenix', 'AZ', '85025');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (38, '055 Glendale Pass', 'Honolulu', 'HI', '96805');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (39, '5 Dawn Avenue', 'Galveston', 'TX', '77554');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (40, '43 Northfield Crossing', 'Lansing', 'MI', '48956');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (41, '638 Merry Alley', 'El Paso', 'TX', '79945');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (42, '4716 Donald Place', 'Grand Rapids', 'MI', '49518');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (43, '60 Manitowish Lane', 'Naples', 'FL', '33961');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (44, '39 Namekagon Lane', 'Florence', 'SC', '29505');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (45, '46304 Havey Pass', 'Winston Salem', 'NC', '27157');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (46, '9103 Dorton Parkway', 'Kansas City', 'MO', '64114');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (47, '85222 Dayton Place', 'Riverside', 'CA', '92519');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (48, '6804 Red Cloud Street', 'Portland', 'ME', '04109');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (49, '65934 Dixon Hill', 'Oklahoma City', 'OK', '73142');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (50, '60681 Blaine Park', 'Pittsburgh', 'PA', '15240');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (51, '768 Waywood Park', 'Akron', 'OH', '44315');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (52, '23259 Shoshone Court', 'Odessa', 'TX', '79764');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (53, '8 Parkside Hill', 'Detroit', 'MI', '48275');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (54, '34907 Hollow Ridge Circle', 'Richmond', 'VA', '23213');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (55, '0 Sutteridge Place', 'Irving', 'TX', '75037');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (56, '59860 Milwaukee Crossing', 'Des Moines', 'IA', '50335');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (57, '609 Emmet Plaza', 'New York City', 'NY', '10009');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (58, '1 Havey Lane', 'Petaluma', 'CA', '94975');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (59, '9 Stuart Pass', 'Buffalo', 'NY', '14205');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (60, '10 Loftsgordon Plaza', 'Charleston', 'WV', '25356');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (61, '0817 Holy Cross Way', 'Bethlehem', 'PA', '18018');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (62, '3 Everett Center', 'Boise', 'ID', '83757');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (63, '53 Hallows Trail', 'Myrtle Beach', 'SC', '29579');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (64, '58 Barby Point', 'Saint Paul', 'MN', '55146');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (65, '4165 Westridge Court', 'Nashville', 'TN', '37205');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (66, '8 Florence Plaza', 'Washington', 'DC', '20244');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (67, '0 Oneill Pass', 'Honolulu', 'HI', '96810');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (68, '159 Northridge Center', 'Los Angeles', 'CA', '90076');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (69, '30 Monterey Pass', 'Panama City', 'FL', '32405');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (70, '0 Jay Junction', 'New Haven', 'CT', '06510');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (71, '067 Pawling Crossing', 'Raleigh', 'NC', '27658');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (72, '85556 La Follette Pass', 'Billings', 'MT', '59112');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (73, '78 Oriole Circle', 'Midland', 'TX', '79710');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (74, '80584 Pepper Wood Drive', 'Springfield', 'IL', '62718');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (75, '3939 Upham Plaza', 'Brooklyn', 'NY', '11225');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (76, '18 Vermont Junction', 'Naples', 'FL', '33961');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (77, '8 Garrison Road', 'Tucson', 'AZ', '85705');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (78, '862 Banding Lane', 'Las Cruces', 'NM', '88006');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (79, '980 Dexter Hill', 'Sioux Falls', 'SD', '57193');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (80, '194 Esker Circle', 'Brooklyn', 'NY', '11236');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (81, '3202 Farmco Road', 'Spokane', 'WA', '99260');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (82, '4 Bunker Hill Avenue', 'New York City', 'NY', '10184');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (83, '0 Carey Circle', 'Richmond', 'VA', '23293');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (84, '31152 Kinsman Terrace', 'Washington', 'DC', '20041');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (85, '9838 7th Parkway', 'New Orleans', 'LA', '70160');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (86, '50 Carpenter Hill', 'Spokane', 'WA', '99205');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (87, '406 Arkansas Court', 'Omaha', 'NE', '68179');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (88, '8308 Macpherson Lane', 'Saint Cloud', 'MN', '56398');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (89, '1 Farmco Road', 'Durham', 'NC', '27710');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (90, '078 Crowley Place', 'Phoenix', 'AZ', '85053');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (91, '65326 Shoshone Parkway', 'Erie', 'PA', '16550');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (92, '0 Marcy Pass', 'Montgomery', 'AL', '36195');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (93, '4 Hintze Hill', 'Montgomery', 'AL', '36177');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (94, '3 Portage Terrace', 'Atlanta', 'GA', '30356');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (95, '141 Buena Vista Crossing', 'Toledo', 'OH', '43666');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (96, '538 Rusk Point', 'Washington', 'DC', '20016');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (97, '8590 Valley Edge Center', 'El Paso', 'TX', '88574');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (98, '14 Larry Center', 'Nashville', 'TN', '37215');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (99, '48892 Bellgrove Plaza', 'San Francisco', 'CA', '94126');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (100, '72450 Dottie Park', 'Little Rock', 'AR', '72209');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (101, '50 Farwell Park', 'Colorado Springs', 'CO', '80945');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (102, '09 Comanche Drive', 'Waco', 'TX', '76796');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (103, '95958 Delaware Road', 'Washington', 'DC', '20425');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (104, '77027 Talisman Court', 'Jackson', 'MS', '39282');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (105, '75 Acker Terrace', 'Green Bay', 'WI', '54313');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (106, '2923 Summer Ridge Pass', 'El Paso', 'TX', '88563');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (107, '5898 Summer Ridge Hill', 'Lansing', 'MI', '48901');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (108, '4 Washington Hill', 'Dallas', 'TX', '75287');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (109, '15 Morrow Circle', 'Hialeah', 'FL', '33013');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (110, '40523 Colorado Hill', 'Corpus Christi', 'TX', '78475');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (111, '56 Florence Drive', 'Boston', 'MA', '02119');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (112, '0 Fairfield Place', 'Cedar Rapids', 'IA', '52410');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (113, '58054 Emmet Avenue', 'Cedar Rapids', 'IA', '52405');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (114, '23 Hagan Crossing', 'Winter Haven', 'FL', '33884');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (115, '5453 Bluestem Park', 'Lansing', 'MI', '48930');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (116, '24 Fremont Point', 'Ashburn', 'VA', '22093');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (117, '4 Crowley Road', 'Beaumont', 'TX', '77713');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (118, '827 Loftsgordon Lane', 'Sparks', 'NV', '89436');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (119, '82 Ryan Way', 'Birmingham', 'AL', '35215');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (120, '034 Bobwhite Terrace', 'Hicksville', 'NY', '11854');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (121, '69295 Schmedeman Plaza', 'Inglewood', 'CA', '90398');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (122, '4 Westport Hill', 'Fort Wayne', 'IN', '46852');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (123, '613 Bonner Place', 'Spring', 'TX', '77388');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (124, '62 Eagan Avenue', 'Saint Cloud', 'MN', '56372');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (125, '47680 Nancy Center', 'New Orleans', 'LA', '70174');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (126, '1 Nelson Parkway', 'Irving', 'TX', '75037');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (127, '6610 Gerald Point', 'Detroit', 'MI', '48242');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (128, '275 Kipling Point', 'Carol Stream', 'IL', '60158');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (129, '06143 Continental Center', 'Bonita Springs', 'FL', '34135');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (130, '86 Park Meadow Plaza', 'Tulsa', 'OK', '74126');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (131, '27208 Stuart Point', 'Sarasota', 'FL', '34276');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (132, '74090 Cody Terrace', 'New Orleans', 'LA', '70116');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (133, '52131 Hayes Point', 'Sterling', 'VA', '20167');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (134, '1582 Garrison Drive', 'New Haven', 'CT', '06538');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (135, '849 Meadow Valley Alley', 'Charleston', 'WV', '25336');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (136, '3 Goodland Center', 'San Diego', 'CA', '92115');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (137, '909 Alpine Point', 'Houston', 'TX', '77070');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (138, '87 Mallard Point', 'Madison', 'WI', '53790');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (139, '59757 Dixon Drive', 'Chicago', 'IL', '60646');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (140, '26 Little Fleur Lane', 'Milwaukee', 'WI', '53285');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (141, '7131 Golf Course Crossing', 'Fresno', 'CA', '93721');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (142, '45 Swallow Way', 'Rochester', 'NY', '14619');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (143, '74707 Upham Way', 'San Bernardino', 'CA', '92410');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (144, '48 Annamark Crossing', 'Cape Coral', 'FL', '33915');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (145, '4249 Tomscot Way', 'Kansas City', 'MO', '64153');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (146, '50 Nancy Trail', 'Kansas City', 'MO', '64144');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (147, '24547 Buena Vista Center', 'Dayton', 'OH', '45408');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (148, '24365 Pankratz Way', 'Apache Junction', 'AZ', '85219');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (149, '5 Mitchell Center', 'Punta Gorda', 'FL', '33982');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (150, '0387 Darwin Drive', 'Denver', 'CO', '80243');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (151, '5537 Nevada Road', 'El Paso', 'TX', '79940');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (152, '6 Warrior Court', 'San Diego', 'CA', '92105');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (153, '19401 Trailsway Parkway', 'Louisville', 'KY', '40298');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (154, '79 Holy Cross Road', 'Green Bay', 'WI', '54313');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (155, '436 Monterey Park', 'Hayward', 'CA', '94544');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (156, '5627 Monument Drive', 'Rochester', 'NY', '14624');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (157, '85 Sloan Park', 'West Palm Beach', 'FL', '33421');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (158, '94 Carioca Hill', 'Montgomery', 'AL', '36104');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (159, '80601 Oneill Terrace', 'Sioux Falls', 'SD', '57198');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (160, '1213 Ilene Road', 'Lynchburg', 'VA', '24503');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (161, '91 Comanche Park', 'Miami Beach', 'FL', '33141');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (162, '89 Sugar Lane', 'Montgomery', 'AL', '36125');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (163, '735 Maywood Street', 'Arlington', 'VA', '22212');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (164, '29118 Logan Court', 'Buffalo', 'NY', '14215');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (165, '2 Mifflin Plaza', 'Wilmington', 'NC', '28410');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (166, '297 Packers Street', 'Wilkes Barre', 'PA', '18768');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (167, '78925 7th Circle', 'Richmond', 'VA', '23285');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (168, '52029 Sullivan Lane', 'Metairie', 'LA', '70033');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (169, '46530 Tennessee Street', 'Albany', 'NY', '12262');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (170, '010 Colorado Point', 'Monticello', 'MN', '55565');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (171, '11 Hudson Plaza', 'Cambridge', 'MA', '02142');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (172, '33 Crownhardt Court', 'Madison', 'WI', '53779');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (173, '3068 Darwin Terrace', 'San Jose', 'CA', '95138');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (174, '50638 Marcy Street', 'Spartanburg', 'SC', '29319');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (175, '02288 Hazelcrest Drive', 'Seattle', 'WA', '98195');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (176, '5 Hollow Ridge Street', 'Boise', 'ID', '83716');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (177, '31 Carpenter Center', 'Athens', 'GA', '30610');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (178, '69 Springs Center', 'Scottsdale', 'AZ', '85260');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (179, '48 Maple Terrace', 'Colorado Springs', 'CO', '80935');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (180, '8 Granby Terrace', 'Chattanooga', 'TN', '37405');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (181, '70 Mockingbird Way', 'Schenectady', 'NY', '12305');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (182, '25 Nancy Street', 'Tacoma', 'WA', '98464');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (183, '81 Main Parkway', 'Abilene', 'TX', '79605');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (184, '5468 Schlimgen Plaza', 'Fort Worth', 'TX', '76110');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (185, '49743 Jenna Crossing', 'Miami', 'FL', '33175');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (186, '36 Swallow Place', 'Memphis', 'TN', '38131');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (187, '948 Mayfield Circle', 'Cleveland', 'OH', '44185');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (188, '03305 Northwestern Parkway', 'Minneapolis', 'MN', '55436');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (189, '2 Fremont Road', 'Garland', 'TX', '75049');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (190, '84226 Nova Road', 'Spring', 'TX', '77386');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (191, '9 Spaight Trail', 'Newark', 'DE', '19725');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (192, '64 Lindbergh Court', 'Brooklyn', 'NY', '11215');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (193, '54 Kings Hill', 'Des Moines', 'IA', '50393');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (194, '1 Twin Pines Street', 'Elmira', 'NY', '14905');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (195, '37 Jackson Hill', 'Kansas City', 'MO', '64109');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (196, '5361 Westend Plaza', 'Dallas', 'TX', '75310');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (197, '42886 Briar Crest Place', 'Washington', 'DC', '20591');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (198, '132 Lawn Crossing', 'Salt Lake City', 'UT', '84135');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (199, '99 Acker Circle', 'Spokane', 'WA', '99220');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (200, '6 Carpenter Avenue', 'Washington', 'DC', '20220');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (201, '57 Ronald Regan Drive', 'Van Nuys', 'CA', '91411');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (202, '655 Rockefeller Junction', 'Atlanta', 'GA', '30358');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (203, '4884 La Follette Court', 'Evansville', 'IN', '47747');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (204, '4 Mayfield Parkway', 'Melbourne', 'FL', '32941');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (205, '4 Golf Way', 'Charlotte', 'NC', '28235');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (206, '0940 Talisman Center', 'Everett', 'WA', '98206');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (207, '0 Quincy Court', 'Baltimore', 'MD', '21229');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (208, '68414 Gina Way', 'Denver', 'CO', '80249');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (209, '7 Lotheville Alley', 'Philadelphia', 'PA', '19115');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (210, '29 Ilene Park', 'Roanoke', 'VA', '24020');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (211, '7 Derek Lane', 'Fairfax', 'VA', '22036');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (212, '92 Fallview Park', 'Huntington', 'WV', '25705');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (213, '268 Fieldstone Drive', 'Salinas', 'CA', '93907');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (214, '38158 Butterfield Point', 'Huntington', 'WV', '25770');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (215, '90 Jay Alley', 'Zephyrhills', 'FL', '33543');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (216, '17088 Rusk Place', 'New York City', 'NY', '10120');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (217, '22257 Almo Place', 'Springfield', 'OH', '45505');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (218, '8662 Lakewood Gardens Way', 'Dayton', 'OH', '45426');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (219, '17 Tennyson Crossing', 'Tacoma', 'WA', '98464');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (220, '94378 Spohn Point', 'Fort Worth', 'TX', '76178');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (221, '48113 La Follette Pass', 'Charlotte', 'NC', '28272');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (222, '105 Kedzie Junction', 'Miami', 'FL', '33111');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (223, '7062 Dapin Crossing', 'Arvada', 'CO', '80005');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (224, '297 Nova Point', 'Salt Lake City', 'UT', '84140');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (225, '0 Carberry Drive', 'Tacoma', 'WA', '98447');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (226, '3 Atwood Drive', 'Midland', 'TX', '79710');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (227, '0338 6th Parkway', 'Daytona Beach', 'FL', '32118');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (228, '963 Fremont Terrace', 'Corpus Christi', 'TX', '78475');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (229, '05771 Menomonie Hill', 'Pasadena', 'TX', '77505');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (230, '408 Larry Drive', 'Memphis', 'TN', '38126');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (231, '61 Bluejay Plaza', 'Mobile', 'AL', '36641');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (232, '89 Thompson Point', 'Pensacola', 'FL', '32511');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (233, '9118 Trailsway Street', 'Springfield', 'MA', '01105');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (234, '18814 Becker Street', 'Washington', 'DC', '20546');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (235, '71364 Morningstar Court', 'Inglewood', 'CA', '90305');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (236, '0 Burrows Crossing', 'Amarillo', 'TX', '79171');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (237, '85861 Northview Plaza', 'Austin', 'TX', '78789');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (238, '1536 Forster Junction', 'Lincoln', 'NE', '68583');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (239, '1 Miller Lane', 'Charlotte', 'NC', '28278');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (240, '2210 Hanson Lane', 'Falls Church', 'VA', '22047');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (241, '5 3rd Terrace', 'Little Rock', 'AR', '72231');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (242, '0 Pearson Terrace', 'Johnson City', 'TN', '37605');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (243, '3324 Evergreen Drive', 'Paterson', 'NJ', '07522');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (244, '3 Express Street', 'Sacramento', 'CA', '94280');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (245, '86608 Northview Court', 'Roanoke', 'VA', '24020');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (246, '7 Beilfuss Alley', 'New York City', 'NY', '10004');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (247, '9 Colorado Plaza', 'Washington', 'DC', '20599');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (248, '342 Pennsylvania Crossing', 'El Paso', 'TX', '88589');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (249, '24890 Dryden Plaza', 'Spring', 'TX', '77386');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (250, '8902 Artisan Court', 'Lakeland', 'FL', '33805');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (251, '38 Logan Point', 'Billings', 'MT', '59105');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (252, '9 Jenifer Plaza', 'Pasadena', 'CA', '91117');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (253, '457 Algoma Hill', 'Atlanta', 'GA', '30336');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (254, '12 Lillian Center', 'Honolulu', 'HI', '96825');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (255, '24 Crescent Oaks Way', 'Las Vegas', 'NV', '89110');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (256, '3 Jana Circle', 'Hagerstown', 'MD', '21747');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (257, '1836 Clove Drive', 'San Bernardino', 'CA', '92410');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (258, '472 Waywood Pass', 'Littleton', 'CO', '80127');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (259, '9764 Veith Parkway', 'Colorado Springs', 'CO', '80925');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (260, '9282 Talmadge Court', 'Los Angeles', 'CA', '90055');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (261, '27 Scofield Center', 'Hialeah', 'FL', '33018');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (262, '538 East Terrace', 'Montgomery', 'AL', '36104');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (263, '04589 Spenser Point', 'Houston', 'TX', '77005');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (264, '14 Texas Point', 'Birmingham', 'AL', '35290');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (265, '623 International Lane', 'Shawnee Mission', 'KS', '66210');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (266, '2 Prentice Crossing', 'El Paso', 'TX', '79928');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (267, '831 Maryland Parkway', 'Arlington', 'VA', '22217');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (268, '1347 Mandrake Crossing', 'Atlanta', 'GA', '30340');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (269, '04 Fieldstone Junction', 'Newark', 'NJ', '07104');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (270, '61854 Mayfield Alley', 'San Antonio', 'TX', '78235');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (271, '14 Oriole Way', 'Los Angeles', 'CA', '90189');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (272, '4 Sunnyside Plaza', 'Greensboro', 'NC', '27455');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (273, '212 Derek Crossing', 'Asheville', 'NC', '28805');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (274, '2991 Gateway Way', 'Mesquite', 'TX', '75185');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (275, '481 Saint Paul Junction', 'Huntington Beach', 'CA', '92648');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (276, '07883 Mendota Alley', 'Greenville', 'SC', '29615');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (277, '29 Dakota Center', 'Los Angeles', 'CA', '90005');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (278, '7934 Sutherland Trail', 'Columbia', 'SC', '29225');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (279, '86608 Grim Drive', 'Saint Louis', 'MO', '63143');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (280, '5 Rigney Drive', 'Saint Petersburg', 'FL', '33710');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (281, '90 Morningstar Alley', 'Saint Petersburg', 'FL', '33710');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (282, '690 Victoria Drive', 'Wilmington', 'NC', '28410');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (283, '4 Doe Crossing Terrace', 'Boca Raton', 'FL', '33432');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (284, '81476 Dunning Pass', 'Louisville', 'KY', '40210');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (285, '275 Clyde Gallagher Place', 'Charleston', 'WV', '25313');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (286, '61777 Fieldstone Junction', 'Cape Coral', 'FL', '33915');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (287, '21597 Talisman Trail', 'Bronx', 'NY', '10474');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (288, '35113 Stone Corner Hill', 'Chula Vista', 'CA', '91913');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (289, '84 Doe Crossing Trail', 'Dallas', 'TX', '75205');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (290, '6 Saint Paul Park', 'Dallas', 'TX', '75241');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (291, '57 Bunker Hill Crossing', 'Richmond', 'VA', '23208');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (292, '5 Reindahl Circle', 'Austin', 'TX', '78744');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (293, '1115 Kropf Court', 'Petaluma', 'CA', '94975');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (294, '6 Moland Center', 'Austin', 'TX', '78737');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (295, '01115 Fieldstone Terrace', 'New York City', 'NY', '10155');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (296, '18 Banding Street', 'Aiken', 'SC', '29805');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (297, '411 Hermina Pass', 'New Orleans', 'LA', '70116');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (298, '159 Monument Plaza', 'Winter Haven', 'FL', '33884');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (299, '671 Montana Place', 'Charleston', 'WV', '25356');
insert into Address (Address_ID, Street_address, City, State_suffix, Postal_Code ) values (300, '48569 Hovde Way', 'Lafayette', 'LA', '70593');
