insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (1, 'Gilbertine Calbreath', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (2, 'Wallas Brandassi', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (3, 'Haleigh Reeken', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (4, 'Howey Colomb', 'Colorado');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (5, 'Dody Climpson', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (6, 'Charmane Furmston', 'New Mexico');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (7, 'Land Tennison', 'Indiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (8, 'Andriette Lidyard', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (9, 'Murray Ovise', 'North Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (10, 'Roobbie Cratchley', 'Virginia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (11, 'Alison Ivanikhin', 'Massachusetts');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (12, 'Hulda Yakebowitch', 'New Mexico');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (13, 'Claiborne Exroll', 'Virginia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (14, 'Darleen Gimbart', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (15, 'Erroll Blenkharn', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (16, 'Lulu Picheford', 'Michigan');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (17, 'Dannie Yeeles', 'Iowa');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (18, 'Rhys MacKeever', 'Michigan');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (19, 'Norton Glyne', 'Kentucky');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (20, 'Kent Felten', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (21, 'Orv Cawthry', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (22, 'Ronny Griffithe', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (23, 'Selma Poon', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (24, 'Dell Gaffney', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (25, 'Goddard Sonley', 'Nevada');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (26, 'Jessalin Dyzart', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (27, 'Minda Enbury', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (28, 'Giorgio Bartrum', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (29, 'Darren Ower', 'New Mexico');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (30, 'Jabez Wigsell', 'Nebraska');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (31, 'Ivan Strewther', 'North Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (32, 'Aeriela Luttgert', 'Kentucky');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (33, 'Caz Borrowman', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (34, 'Stacia Giacomasso', 'Kansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (35, 'Dennie Easterling', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (36, 'Mendie Mourge', 'Indiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (37, 'Cissiee Koubu', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (38, 'Kandace Grindell', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (39, 'Muffin Deinert', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (40, 'Andeee McCall', 'Kansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (41, 'Petey Leary', 'Idaho');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (42, 'Kerry Etherson', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (43, 'Dynah Whittuck', 'District of Columbia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (44, 'Rasla Hanford', 'Nevada');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (45, 'Olvan Izaac', 'Kansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (46, 'Deni Eicke', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (47, 'Vivienne Philpault', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (48, 'Billie McInteer', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (49, 'Allard Hearthfield', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (50, 'Jean Butlin', 'Wisconsin');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (51, 'Thorin Branton', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (52, 'Amata Kemson', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (53, 'Evita Siviter', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (54, 'Ameline Reford', 'Ohio');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (55, 'Vale Toor', 'Tennessee');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (56, 'Jeth Joire', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (57, 'Saxon Czajkowska', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (58, 'Basilius Yakutin', 'North Dakota');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (59, 'Dael Eskrigg', 'Nevada');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (60, 'Reginauld Bleibaum', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (61, 'Wendie Rostern', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (62, 'Hazlett Niche', 'South Dakota');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (63, 'Merrill Kingswell', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (64, 'Vanny Farthing', 'Tennessee');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (65, 'Locke Grinyer', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (66, 'Catherin Mathiot', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (67, 'Gonzalo Blaksland', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (68, 'Faunie Kamall', 'Michigan');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (69, 'Lavinia Vittet', 'Indiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (70, 'Kasey Eykel', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (71, 'Ginger Titcom', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (72, 'Meyer Harrington', 'Missouri');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (73, 'Aleta Gilphillan', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (74, 'Anetta Blabber', 'Wisconsin');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (75, 'Humbert Rubenczyk', 'Virginia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (76, 'Genevra Fiddeman', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (77, 'Malcolm Tither', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (78, 'Seward Richel', 'Virginia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (79, 'Kare Heatherington', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (80, 'Reece Sandeman', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (81, 'Ignace Couronne', 'Indiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (82, 'Darell Foskin', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (83, 'Noemi Duchesne', 'Indiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (84, 'Rahal Bouts', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (85, 'Hildagarde Nairn', 'District of Columbia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (86, 'Laughton Oxenford', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (87, 'Bennett Babber', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (88, 'Garrek Hearl', 'Colorado');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (89, 'Gelya Rowbottom', 'Virginia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (90, 'Olympia Bentame', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (91, 'Thorsten Dougan', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (92, 'Kitti Nisard', 'Alabama');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (93, 'Minne Heberden', 'Massachusetts');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (94, 'Babette Studdert', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (95, 'Goldy Cotherill', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (96, 'Arlan Kettlesting', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (97, 'Nissy Jozefowicz', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (98, 'Diana Bennis', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (99, 'Rogers McCambridge', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (100, 'Arther Maybery', 'Tennessee');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (101, 'Carolyn Berzin', 'Missouri');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (102, 'Gaven Attwool', 'Iowa');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (103, 'Humberto Tarr', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (104, 'Elspeth Byre', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (105, 'Beale Pavlenkov', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (106, 'Amble Wolseley', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (107, 'Staci Giacobilio', 'District of Columbia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (108, 'Leland Pinney', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (109, 'Bobbye Grinyakin', 'Minnesota');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (110, 'Bettye Dary', 'Colorado');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (111, 'Eolanda Fleay', 'Missouri');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (112, 'Milena Nanetti', 'Wisconsin');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (113, 'Leigh Jenson', 'North Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (114, 'Kip Eliet', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (115, 'Byrle Cafe', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (116, 'Cesya Pelham', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (117, 'Raphael Risson', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (118, 'Karly Trudgion', 'Iowa');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (119, 'Tommie Bolitho', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (120, 'Tyrus McKue', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (121, 'Salomi Pifford', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (122, 'Zulema O''Fearguise', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (123, 'Kevan Toderi', 'Kentucky');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (124, 'Elie Grayston', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (125, 'Mel Aizikovitch', 'Maryland');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (126, 'Tillie Chree', 'Kentucky');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (127, 'Lief Winham', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (128, 'Morgan Dwelly', 'Iowa');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (129, 'Mignonne Bambridge', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (130, 'Honor Boobyer', 'Utah');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (131, 'Evered Peers', 'Michigan');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (132, 'Gates Twohig', 'Virginia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (133, 'Ronna Beaves', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (134, 'Alex Virr', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (135, 'Jobie Prestie', 'Ohio');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (136, 'Elsey Flaws', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (137, 'Lindsey Markie', 'Massachusetts');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (138, 'Jess McBride', 'Washington');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (139, 'Meggie Solon', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (140, 'Nicholle Gynn', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (141, 'Paige Graddon', 'Indiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (142, 'Eleanora Rives', 'Michigan');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (143, 'Bertram Herries', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (144, 'Fidole Adamec', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (145, 'Angie Ryding', 'Iowa');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (146, 'Dulcy Priestland', 'Oregon');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (147, 'Moritz Laxon', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (148, 'Dacey Balfre', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (149, 'Mervin Merrigan', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (150, 'Remy Lardier', 'Minnesota');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (151, 'Silvester Conew', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (152, 'Shelly De Cruce', 'Alabama');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (153, 'Claus Messiter', 'New Jersey');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (154, 'Josh Tyler', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (155, 'Fredrick Ewell', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (156, 'Tara Corking', 'North Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (157, 'Cami Berkery', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (158, 'Archibold Kempston', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (159, 'Erich Eaglen', 'Michigan');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (160, 'Margaret Few', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (161, 'Eden Spain-Gower', 'Alabama');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (162, 'Marleen Cozens', 'Massachusetts');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (163, 'Pebrook Romans', 'Oregon');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (164, 'Lorilyn Izakson', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (165, 'Kahaleel Sherborne', 'North Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (166, 'Yuma Samter', 'Oregon');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (167, 'Margarethe Rochewell', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (168, 'Florri Iacovolo', 'District of Columbia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (169, 'Iseabal Cearley', 'Utah');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (170, 'Huntlee Tanti', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (171, 'Gregoire Tuppeny', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (172, 'Bat McIlvaney', 'Massachusetts');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (173, 'Teresina Tatersale', 'Idaho');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (174, 'April Pennell', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (175, 'Holden Brook', 'Oregon');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (176, 'Chrisse Spincks', 'Iowa');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (177, 'Constancia Brock', 'Minnesota');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (178, 'Thomasina Hendrix', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (179, 'Henrietta Milkins', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (180, 'Averell MacLaig', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (181, 'Veda Kitney', 'Kentucky');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (182, 'Pieter Minton', 'North Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (183, 'Charmane Gubbin', 'Alabama');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (184, 'Sara Aartsen', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (185, 'Bart Scoates', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (186, 'Katie Rembrandt', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (187, 'Vevay Fenny', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (188, 'Quill Joynes', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (189, 'Michaella Terne', 'Michigan');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (190, 'Claybourne McSkin', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (191, 'Koralle Ferrino', 'Missouri');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (192, 'Barry Threlfall', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (193, 'Erek Dyhouse', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (194, 'Barbey Widocks', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (195, 'Aldous Cocker', 'Washington');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (196, 'Joyan Pellman', 'Ohio');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (197, 'Maxy Aherne', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (198, 'Ransom Robison', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (199, 'Elsa Crittal', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (200, 'Cello Sheringham', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (201, 'Gale Guye', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (202, 'Trula Rolin', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (203, 'Avery Gladwin', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (204, 'Murray Geddis', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (205, 'Brewster Drewes', 'Ohio');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (206, 'Duffie Deeney', 'Missouri');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (207, 'Inessa Ullock', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (208, 'Millard Toolan', 'District of Columbia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (209, 'Brita Baert', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (210, 'Gabriele Aronin', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (211, 'Hasheem Ratie', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (212, 'Lorelei Kettridge', 'Tennessee');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (213, 'Eamon Giorgioni', 'Washington');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (214, 'Kania Henrych', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (215, 'Broddy Gierck', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (216, 'Hazel Aulsford', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (217, 'Elene McReynolds', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (218, 'Arvie Mayell', 'Alabama');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (219, 'Baxy Knoble', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (220, 'Maiga Englishby', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (221, 'Maury Tomanek', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (222, 'Netti Durham', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (223, 'Frazier Titterton', 'Virginia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (224, 'Sharla Zamudio', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (225, 'Jerome Rieflin', 'Washington');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (226, 'Isobel Piegrome', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (227, 'Jillayne Strong', 'Nevada');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (228, 'Itch MacConnechie', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (229, 'Avivah Diggons', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (230, 'Darya De Malchar', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (231, 'Francklyn Tripean', 'Arkansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (232, 'Inness Ubank', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (233, 'Dalton Bedrosian', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (234, 'Norbert Taynton', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (235, 'Brigg Tarling', 'Oklahoma');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (236, 'Adelina Perllman', 'Washington');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (237, 'Tess Spellicy', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (238, 'Gare Lipyeat', 'Colorado');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (239, 'Bebe Challener', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (240, 'Tull MacIllrick', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (241, 'Anestassia Sendall', 'Indiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (242, 'Ermin Pach', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (243, 'Leora Stote', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (244, 'Welbie Eary', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (245, 'Brunhilde Thomann', 'Minnesota');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (246, 'Kellia Yashanov', 'Texas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (247, 'Sallyann Losty', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (248, 'Caldwell Le feaver', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (249, 'Lorelle Hiscoke', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (250, 'Lucila Schultheiss', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (251, 'Marty Eat', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (252, 'Edgar Darke', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (253, 'Stacy Mandrier', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (254, 'Stanislas Jerok', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (255, 'Gertruda Wims', 'Louisiana');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (256, 'Evelina Forrest', 'Delaware');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (257, 'Ross Fishly', 'Colorado');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (258, 'Rolando Sirr', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (259, 'Larina Twell', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (260, 'Georgy Troucher', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (261, 'Harriot Mayer', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (262, 'Domenico Baughan', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (263, 'Mohandas Craigs', 'Nevada');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (264, 'Elsey Batchelar', 'Illinois');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (265, 'Murdoch Colecrough', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (266, 'Tisha Chomicz', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (267, 'Vincents Stihl', 'Kansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (268, 'Reeba Casel', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (269, 'Sandy Colquhoun', 'Arkansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (270, 'Juditha Cortez', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (271, 'Elwin Mulheron', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (272, 'Avictor O''Shee', 'Kentucky');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (273, 'Hanny Kollas', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (274, 'Peyter Pack', 'Nevada');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (275, 'Byron Lampitt', 'Kentucky');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (276, 'Francklin Welbourn', 'Georgia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (277, 'Lief Pennycuick', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (278, 'Anita Alwell', 'Kansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (279, 'Fredra Bicker', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (280, 'Jerri Gaveltone', 'Florida');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (281, 'Kingsly Skull', 'Oklahoma');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (282, 'Iain Masdon', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (283, 'Phyllys Allberry', 'Washington');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (284, 'Sibilla Griffoen', 'Nevada');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (285, 'Di Lamy', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (286, 'Averell Deakan', 'North Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (287, 'Randolf Cornelleau', 'Kansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (288, 'Eldon Lamming', 'District of Columbia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (289, 'Brett Borrell', 'California');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (290, 'Marten Simek', 'Arizona');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (291, 'Fayre Ayer', 'Arkansas');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (292, 'Malissa Barr', 'District of Columbia');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (293, 'Norean Gilhooly', 'Connecticut');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (294, 'Barbaraanne Records', 'New York');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (295, 'Burnard Maurice', 'Pennsylvania');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (296, 'Clayborne Alvy', 'Utah');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (297, 'Carlita Gregr', 'Missouri');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (298, 'Cairistiona Pedrozzi', 'South Carolina');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (299, 'Iona Horning', 'Alabama');
insert into sales_representative (SDR_ID, SDR_NAME, Territory) values (300, 'Dorelle Thornbarrow', 'Texas');
